
import { PLAYER_SIZE } from './player';

// --- ARRUACEIRO ---
export const ENEMY_ARROCEIRO_SIZE = PLAYER_SIZE;
export const ENEMY_ARROCEIRO_INITIAL_HEALTH = 10;
export const ENEMY_ARROCEIRO_DAMAGE = 2;
export const ENEMY_ARROCEIRO_BASE_SPEED = 1.8;
export const ENEMY_ARROCEIRO_ATTACK_RANGE_SQUARED = (PLAYER_SIZE / 2 + ENEMY_ARROCEIRO_SIZE / 2 + 5) ** 2;
export const ENEMY_ARROCEIRO_ATTACK_COOLDOWN = 800;
export const ENEMY_ARROCEIRO_MONEY_VALUE = 2;
export const MAX_ARROCEIROS_WAVE_BASE = 5;

// --- CÃO DE FAZENDA ---
export const ENEMY_CAODEFAZENDA_SIZE = PLAYER_SIZE * 0.8;
export const ENEMY_CAODEFAZENDA_INITIAL_HEALTH = 12;
export const ENEMY_CAODEFAZENDA_DAMAGE = 4;
export const ENEMY_CAODEFAZENDA_BASE_SPEED = 2.5;
export const ENEMY_CAODEFAZENDA_ATTACK_RANGE_SQUARED = (PLAYER_SIZE / 2 + ENEMY_CAODEFAZENDA_SIZE / 2 + 5) ** 2;
export const ENEMY_CAODEFAZENDA_ATTACK_COOLDOWN = 700;
export const ENEMY_CAODEFAZENDA_MONEY_VALUE = 1;
export const MAX_CAES_WAVE_BASE = 6;
export const CAO_SPAWN_BATCH_SIZE = 3;

// --- PISTOLEIRO ---
export const ENEMY_PISTOLEIRO_SIZE = PLAYER_SIZE;
export const ENEMY_PISTOLEIRO_INITIAL_HEALTH = 15;
export const ENEMY_PISTOLEIRO_DAMAGE = 5;
export const ENEMY_PISTOLEiro_BASE_SPEED = 1.5;
export const ENEMY_PISTOLEIRO_MONEY_VALUE = 4;
export const ENEMY_PISTOLEIRO_ATTACK_RANGE_SQUARED = (350) ** 2;
export const ENEMY_PISTOLEIRO_ATTACK_COOLDOWN = 2500;
export const ENEMY_PISTOLEIRO_MELEE_RANGE_SQUARED = (PLAYER_SIZE / 2 + ENEMY_PISTOLEIRO_SIZE / 2 + 10) ** 2;
export const MAX_PISTOLEIROS_WAVE_BASE = 2;
export const PISTOLEIRO_SPAWN_BATCH_SIZE = 2;

// --- MINERADOR ---
export const ENEMY_MINERADOR_SIZE = PLAYER_SIZE * 1.1;
export const ENEMY_MINERADOR_INITIAL_HEALTH = 18;
export const ENEMY_MINERADOR_DAMAGE = 7;
export const ENEMY_MINERADOR_BASE_SPEED = 1.2;
export const ENEMY_MINERADOR_MONEY_VALUE = 5;
export const ENEMY_MINERADOR_ATTACK_RANGE_SQUARED = (PLAYER_SIZE / 2 + ENEMY_MINERADOR_SIZE / 2 + 8) ** 2;
export const ENEMY_MINERADOR_ATTACK_COOLDOWN = 1200;
export const MAX_MINERADORES_WAVE_BASE = 1;
export const MINERADOR_SPAWN_BATCH_SIZE = 1;

// --- VIGIA ---
export const ENEMY_VIGIA_SIZE = PLAYER_SIZE;
export const ENEMY_VIGIA_INITIAL_HEALTH = 25;
export const ENEMY_VIGIA_DAMAGE = 6;
export const ENEMY_VIGIA_BASE_SPEED = 1.6;
export const ENEMY_VIGIA_MONEY_VALUE = 6;
export const ENEMY_VIGIA_ATTACK_RANGE_SQUARED = (400 * 400);
export const ENEMY_VIGIA_ATTACK_COOLDOWN = 3000;
export const MAX_VIGIAS_WAVE_BASE = 1;
export const VIGIA_SPAWN_BATCH_SIZE = 1;

// --- BRUTO BOYLE ---
export const ENEMY_BRUTOBOYLE_SIZE = PLAYER_SIZE * 1.2;
export const ENEMY_BRUTOBOYLE_INITIAL_HEALTH = 40;
export const ENEMY_BRUTOBOYLE_DAMAGE = 10;
export const ENEMY_BRUTOBOYLE_BASE_SPEED = 1.0;
export const ENEMY_BRUTOBOYLE_MONEY_VALUE = 8;
export const ENEMY_BRUTOBOYLE_ATTACK_RANGE_SQUARED = (PLAYER_SIZE / 2 + ENEMY_BRUTOBOYLE_SIZE / 2 + 10) ** 2;
export const ENEMY_BRUTOBOYLE_ATTACK_COOLDOWN = 1500;
export const MAX_BRUTOS_WAVE_BASE = 1;
export const BRUTO_SPAWN_BATCH_SIZE = 1;

// --- SABOTADOR ---
export const ENEMY_SABOTADOR_SIZE = PLAYER_SIZE * 0.9;
export const ENEMY_SABOTADOR_INITIAL_HEALTH = 20;
export const ENEMY_SABOTADOR_DAMAGE = 15;
export const ENEMY_SABOTADOR_BASE_SPEED = 2.8;
export const ENEMY_SABOTADOR_MONEY_VALUE = 7;
export const ENEMY_SABOTADOR_DETONATION_RANGE_SQUARED = (PLAYER_SIZE * 1.2) ** 2;
export const ENEMY_SABOTADOR_EXPLOSION_RADIUS_SQUARED = (PLAYER_SIZE * 2.5) ** 2;
export const ENEMY_SABOTADOR_DETONATION_TIMER_DURATION = 700;
export const MAX_SABOTADORES_WAVE_BASE = 1;
export const SABOTADOR_SPAWN_BATCH_SIZE = 1;

// --- MCGRAW ---
export const ENEMY_MCGRAW_SIZE = PLAYER_SIZE;
export const ENEMY_MCGRAW_INITIAL_HEALTH = 30;
export const ENEMY_MCGRAW_DAMAGE = 12;
export const ENEMY_MCGRAW_BASE_SPEED = 1.1;
export const ENEMY_MCGRAW_MONEY_VALUE = 10;
export const ENEMY_MCGRAW_ATTACK_RANGE_SQUARED = (550 * 550);
export const ENEMY_MCGRAW_ATTACK_COOLDOWN = 4000;
export const ENEMY_MCGRAW_TELEGRAPH_DURATION = 1500;
export const MAX_MCGRAW_WAVE_BASE = 1;
export const MCGRAW_SPAWN_BATCH_SIZE = 1;

// --- DESERTOR ---
export const ENEMY_DESERTOR_SIZE = PLAYER_SIZE;
export const ENEMY_DESERTOR_INITIAL_HEALTH = 35;
export const ENEMY_DESERTOR_DAMAGE = 8;
export const ENEMY_DESERTOR_BASE_SPEED = 2.2;
export const ENEMY_DESERTOR_MONEY_VALUE = 9;
export const ENEMY_DESERTOR_ATTACK_RANGE_SQUARED = (300 * 300);
export const ENEMY_DESERTOR_ATTACK_COOLDOWN = 1800;
export const ENEMY_DESERTOR_SHOTS_IN_BURST = 2;
export const ENEMY_DESERTOR_BURST_DELAY = 150;
export const MAX_DESERTOR_WAVE_BASE = 1;
export const DESERTOR_SPAWN_BATCH_SIZE = 1;

// --- DRONE ---
export const ENEMY_DRONE_SIZE = PLAYER_SIZE * 0.6;
export const ENEMY_DRONE_INITIAL_HEALTH = 15;
export const ENEMY_DRONE_DAMAGE = 3;
export const ENEMY_DRONE_BASE_SPEED = 2.8;
export const ENEMY_DRONE_MONEY_VALUE = 0;
export const ENEMY_DRONE_ATTACK_RANGE_SQUARED = (PLAYER_SIZE / 2 + ENEMY_DRONE_SIZE / 2 + 3) ** 2;
export const ENEMY_DRONE_ATTACK_COOLDOWN = 1000;

// --- BOSS: CAPTAIN MCGRAW ---
export const ENEMY_CAPTAINMCGRAW_SIZE = PLAYER_SIZE * 1.1;
export const ENEMY_CAPTAINMCGRAW_INITIAL_HEALTH = 180;
export const ENEMY_CAPTAINMCGRAW_RIFLE_DAMAGE = 20;
export const ENEMY_CAPTAINMCGRAW_BASE_SPEED = 0.9;
export const ENEMY_CAPTAINMCGRAW_MONEY_VALUE = 100;
export const ENEMY_CAPTAINMCGRAW_RIFLE_ATTACK_RANGE_SQUARED = (650 * 650);
export const ENEMY_CAPTAINMCGRAW_RIFLE_ATTACK_COOLDOWN = 5000;
export const ENEMY_CAPTAINMCGRAW_RIFLE_TELEGRAPH_DURATION = 2000;
export const ENEMY_CAPTAINMCGRAW_DRONE_SPAWN_COOLDOWN = 8000;
export const ENEMY_CAPTAINMCGRAW_MAX_ACTIVE_DRONES = 3;

// --- BOSS: BIG DOYLE ---
export const ENEMY_BIGDOYLE_SIZE = PLAYER_SIZE * 1.6;
export const ENEMY_BIGDOYLE_INITIAL_HEALTH = 200;
export const ENEMY_BIGDOYLE_MELEE_DAMAGE = 15;
export const ENEMY_BIGDOYLE_BARREL_DAMAGE = 25;
export const ENEMY_BIGDOYLE_BASE_SPEED = 0.8;
export const ENEMY_BIGDOYLE_MONEY_VALUE = 75;
export const ENEMY_BIGDOYLE_MELEE_ATTACK_RANGE_SQUARED = (PLAYER_SIZE / 2 + ENEMY_BIGDOYLE_SIZE / 2 + 15) ** 2;
export const ENEMY_BIGDOYLE_MELEE_ATTACK_COOLDOWN = 2500;
export const ENEMY_BIGDOYLE_BARREL_THROW_COOLDOWN = 6000;
export const ENEMY_BIGDOYLE_BARREL_THROW_RANGE_SQUARED = (450 * 450);

// --- BOSS: DOM GAEL ---
export const ENEMY_DOMGAEL_SIZE = PLAYER_SIZE * 1.05;
export const ENEMY_DOMGAEL_INITIAL_HEALTH = 160;
export const ENEMY_DOMGAEL_PISTOL_DAMAGE = 12;
export const ENEMY_DOMGAEL_KNIFE_DAMAGE = 18;
export const ENEMY_DOMGAEL_BASE_SPEED = 2.5;
export const ENEMY_DOMGAEL_MONEY_VALUE = 120;
export const ENEMY_DOMGAEL_PISTOL_ATTACK_RANGE_SQUARED = (400 * 400);
export const ENEMY_DOMGAEL_KNIFE_ATTACK_RANGE_SQUARED = (PLAYER_SIZE * 1.8) ** 2;
export const ENEMY_DOMGAEL_PISTOL_COOLDOWN = 1500;
export const ENEMY_DOMGAEL_KNIFE_COOLDOWN = 800;
export const ENEMY_DOMGAEL_ALLY_SPAWN_COOLDOWN = 12000;
export const ENEMY_DOMGAEL_MAX_ACTIVE_ALLIES = 2;
export const ENEMY_DOMGAEL_DASH_COOLDOWN = 6000;
export const ENEMY_DOMGAEL_DASH_DURATION = 250;
export const ENEMY_DOMGAEL_DASH_SPEED_MULTIPLIER = 2.0;
export const ENEMY_DOMGAEL_MODE_SWITCH_COOLDOWN = 3000;

// --- BOSS: CALEB HODGE ---
export const ENEMY_CALEBHODGE_SIZE = PLAYER_SIZE * 1.1;
export const ENEMY_CALEBHODGE_INITIAL_HEALTH = 220;
export const ENEMY_CALEBHODGE_DYNAMITE_DAMAGE = 18;
export const ENEMY_CALEBHODGE_BASE_SPEED = 0.9;
export const ENEMY_CALEBHODGE_MONEY_VALUE = 150;
export const ENEMY_CALEBHODGE_DYNAMITE_THROW_COOLDOWN = 5000;
export const ENEMY_CALEBHODGE_DYNAMITE_THROW_RANGE_SQUARED = (400 * 400);
export const ENEMY_CALEBHODGE_FISSURE_CREATE_COOLDOWN = 8000;
export const ENEMY_CALEBHODGE_MAX_ACTIVE_FISSURES = 3;

// --- FISSURE TRAP ---
export const FISSURE_TRAP_WIDTH = PLAYER_SIZE * 4;
export const FISSURE_TRAP_HEIGHT = PLAYER_SIZE * 1.5;
export const FISSURE_TRAP_DURATION = 10000;
export const FISSURE_TRAP_DAMAGE = 15;
export const FISSURE_PLAYER_DAMAGE_COOLDOWN = 1000;

    